import numpy as np
import pacfish as pf
PATH = r"W:\Group\Data\20250611_OpenQPATData/"

print("- OpenPATData")
print(" material_mapping.json | JSON file mapping the segmenattion labels to the phantom materials.")
print("-- DIS")
print("--- processed")
print("---- T.5.1.a")
file = np.load(f"{PATH}/DIS/processed/T.5.1.a/T.5.1.npz")
print("   | T.5.1.npz", "|", type(file), "|",  list(file.keys()))
print("   | T.5.1.png", "| Visualisation of the materials absorption and scattering properties.")
print("----- 1")
print("    | 1.rxt | text file containing the measurements of total transmittance and reflectance of the measurement.")
print("    | 1.txt | text file containing the estimated absorption and reduced cattering coefficients in [1/mm].")
print("----- 2 - 6")
print("--- raw")
print("---- T.5.1.a")
print("   | 1_R_OpenPort.txt", "| Minimum reflectance calibration measurement.")
print("   | 1_R_RefInPlace.txt", "| Maximum reflectance calibration measurement.")
print("   | 1_T_BlockBeam.txt", "| Minimum transmittance calibration measurement.")
print("   | 1_T_IncBeam.txt", "| Maximum transmittance calibration measurement.")
print("   | recipe.txt", "| Listing of the amounts of all chemicals for fabricating the phantom.")
print("---- ...")
print("----- 1")
print("    | 1_R_SampInPlace.rxt | Total reflectance with the sample in place.")
print("    | 1_T_SampInPlace.txt | Total transmittance with the sample in place.")
print("    | thickness.txt | Caliper thickness measurements with mm units.")
print("----- 2 - 6")
print("-- invision")
print("--- labels")
file = np.load(f"{PATH}/invision/labels/P.5.1.npy")
print("   | T.5.1.npy", "|", type(file), "|",  np.shape(file))
print("   | ...")
print("--- mua")
file = np.load(f"{PATH}/invision/mua/P.5.1_700.npy")
print("   | T.5.1_700.npy", "|", type(file), "|",  np.shape(file))
print("   | ...")
print("--- musp")
file = np.load(f"{PATH}/invision/musp/P.5.1_700.npy")
print("   | T.5.1_700.npy", "|", type(file), "|",  np.shape(file))
print("   | ...")
print("--- raw")
file = pf.load_data(f"{PATH}/invision/raw/P.5.1_700_ipasc.hdf5")
print("   | P.5.1_700_ipasc.hdf5", "|", type(file), "| binary_time_series_data shape:",  np.shape(file.binary_time_series_data))
print("   | ...")
print("--- recon")
file = np.load(f"{PATH}/invision/recon/P.5.1_700.npy")
print("   | T.5.1_700.npy", "|", type(file), "|",  np.shape(file))
print("   | ...")
print("-- tropus")
print("--- labels")
file = np.load(f"{PATH}/tropus/labels/P.5.1.npy")
print("   | T.5.1.npy", "|", type(file), "|",  np.shape(file))
print("   | ...")
print("--- mua")
file = np.load(f"{PATH}/tropus/mua/P.5.1_700.npy")
print("   | T.5.1_700.npy", "|", type(file), "|",  np.shape(file))
print("   | ...")
print("--- musp")
file = np.load(f"{PATH}/tropus/musp/P.5.1_700.npy")
print("   | T.5.1_700.npy", "|", type(file), "|",  np.shape(file))
print("   | ...")
print("--- raw")
file = pf.load_data(f"{PATH}/tropus/raw/P.5.1_700_ipasc.hdf5")
print("   | P.5.1_700_ipasc.hdf5", "|", type(file), "| binary_time_series_data shape:",  np.shape(file.binary_time_series_data))
print("   | ...")
print("--- recon")
file = np.load(f"{PATH}/tropus/recon/P.5.1_700.npy")
print("   | T.5.1_700.npy", "|", type(file), "|",  np.shape(file))
print("   | ...")
print("-- svot")
print("--- labels")
file = np.load(f"{PATH}/svot/labels/P.5.1.npz")
print("   | T.5.1.npy", "|", type(file), "|",  list(file.keys()), "|",  np.shape(file["data"]))
print("   | ...")
print("--- mua")
file = np.load(f"{PATH}/svot/mua/P.5.1_700.npz")
print("   | T.5.1_700.npy", "|", type(file), "|",  list(file.keys()), "|",  np.shape(file["data"]))
print("   | ...")
print("--- musp")
file = np.load(f"{PATH}/svot/musp/P.5.1_700.npz")
print("   | T.5.1_700.npy", "|", type(file), "|",  list(file.keys()), "|",  np.shape(file["data"]))
print("   | ...")
print("--- recon")
file = np.load(f"{PATH}/svot/recon/P.5.1_700.npy")
print("   | T.5.1_700.npy", "|", type(file), "|",  np.shape(file))
print("   | ...")
